import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@okmtyuta/awesome-css/reset.css'
import { Frame } from '@okmtyuta/amatelas-react/server'
import '@okmtyuta/amatelas-react/style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Frame>{children}</Frame>
      </body>
    </html>
  )
}
