name: build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.8.0

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # - name: Build Auth API
      #   run: pnpm build:auth:api

      # - name: Build Auth Client
      #   run: pnpm build:auth:client

      - name: Build About Client
        run: pnpm build:about:client

      - name: Build Blog Client
        run: pnpm build:blog:client

      - name: Build Console Client
        run: pnpm build:console:client
